services:
  users-db:
    image: postgres:15-alpine
    container_name: riff_users
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - riff-network

  users-mongo:
    image: mongo:6.0
    container_name: riff_users_stats
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - riff-network

  users-rabbit:
    image: rabbitmq:3.12-management-alpine
    container_name: riff_users_rabbit
    restart: always
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - riff-network

  users-ms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riff_users_ms
    restart: always
    ports:
      - ${PORT:-3003}:${PORT:-3003}
    environment:
      - PORT=${PORT:-3003}
      - USERS_MS_HOST=0.0.0.0
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@users-db:5432/${DB_NAME}?schema=public
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@users-mongo:27017/${MONGO_DB_NAME}?authSource=admin
      - RABBIT_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@users-rabbit:5672
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      users-db:
        condition: service_healthy
      users-mongo:
        condition: service_healthy
      users-rabbit:
        condition: service_healthy
    networks:
      - riff-network

volumes:
  postgres_data:
  mongo_data:
  rabbit_data:

networks:
  riff-network:
    external: true
