services:
  auth-db:
    image: postgres:15-alpine
    container_name: riff_auth
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  auth-mongo:
    image: mongo:6.0
    container_name: riff_auth_stats
    restart: always
    volumes:
      - ./mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: riff_rabbit
    restart: always
    ports:
      - ${RABBITMQ_PORT}:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq