services:
  users-db:
    image: postgres:15-alpine
    container_name: riff_users
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - users-network

  users-mongo:
    image: mongo:6.0
    container_name: riff_users_stats
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}